const DELETE_POST = 'DELETE_POST';
const DELETE_COMMENT = 'DELETE_COMMENT';
const EDIT_COMMENT = 'EDIT_COMMENT';
const ADD_COMMENT = 'ADD_COMMENT';

module.exports = { DELETE_POST, DELETE_COMMENT, EDIT_COMMENT, ADD_COMMENT };