const DELETE_POST = 'DELETE_POST';
const DELETE_COMMENT = 'DELETE_COMMENT';
const EDIT_COMMENT = 'EDIT_COMMENT';
const ADD_COMMENT = 'ADD_COMMENT';
const ADD_POST = 'ADD_POST';
const EDIT_POST = 'EDIT_POST';
const LOAD_POSTS = 'LOAD_POSTS';
const LOAD_POST = 'LOAD_POST';
const CLEAR_CURRENT_POST = 'CLEAR_CURRENT_POST';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const LOGIN_ERROR = 'LOGIN_ERROR';
const REGISTER_ERROR = 'REGISTER_ERROR';

module.exports = {
    LOGIN,
    LOGOUT,
    LOGIN_ERROR,
    REGISTER_ERROR,
    DELETE_POST,
    DELETE_COMMENT,
    EDIT_COMMENT,
    ADD_COMMENT,
    ADD_POST,
    EDIT_POST,
    LOAD_POSTS,
    LOAD_POST,
    CLEAR_CURRENT_POST
};